language: python

dist: trusty
sudo: required

notifications:
    email: false

before_install:
    - pyenv global 2.7 3.5
    - pip install tox
    - pip install python-coveralls

script:
    - tox

after_success:
  - coveralls
